import { Inter } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/components/Navbar";
import FooterCom from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#D9D9D9]">
          <div className=" mx-auto">
            <NavbarComponent></NavbarComponent>
            {children}
            <FooterCom></FooterCom>
          </div>
        </div>
      </body>
    </html>
  );
}
