import { Inter } from 'next/font/google'
import './globals.css'
import NavbarComponent from '@/components/Navbar'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='max-w-7xl mx-auto'>
          <NavbarComponent></NavbarComponent>
          {children}
        </div>
      </body>
    </html>
  )
}
