"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/components/Navbar";
import FooterCom from "@/components/Footer/Footer";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/Provider/AuthProvider";


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#D9D9D9]">
          <div className="mx-auto">
            <AuthProvider>
              <NavbarComponent></NavbarComponent>
              {children}
              <FooterCom></FooterCom>
              <Toaster />
            </AuthProvider>

          </div>
        </div>
      </body>
    </html>
  );
}
